services:
  postgres:
    image: postgres:16
    container_name: tfg-postgres
    environment:
      POSTGRES_DB: tfg_db
      POSTGRES_USER: tfg_user
      POSTGRES_PASSWORD: tfg_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfg_user -d tfg_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
