spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tfg_db}
spring.datasource.username=${DB_USER:tfg_user}
spring.datasource.password=${DB_PASS:tfg_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.error.include-message=always

