spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tfg_db}
spring.datasource.username=${DB_USER:tfg_user}
spring.datasource.password=${DB_PASS:tfg_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.error.include-message=always
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

app.jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
# 1h en milisegundos
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
